// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function InitRegister(arg1) {
  return window['go']['main']['App']['InitRegister'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function SetRecipient(arg1) {
  return window['go']['main']['App']['SetRecipient'](arg1);
}

export function Verify2FA(arg1, arg2) {
  return window['go']['main']['App']['Verify2FA'](arg1, arg2);
}

export function VerifyCode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['VerifyCode'](arg1, arg2, arg3, arg4, arg5);
}
