// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteMessage(arg1:number):Promise<void>;

export function GetHistory():Promise<Array<main.Message>>;

export function InitRegister(arg1:string):Promise<Record<string, any>>;

export function Login(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SelectFile():Promise<Record<string, any>>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetRecipient(arg1:number):Promise<void>;

export function Verify2FA(arg1:number,arg2:string):Promise<Record<string, any>>;

export function VerifyCode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Record<string, any>>;
